# Generated by Django 3.1.4 on 2021-03-05 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210305_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.AddField(
            model_name='task',
            name='event_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
